#!/usr/bin/env bash

set -o errexit # Exit when command fails
set -o pipefail # Exit when command in pipeline fails

# Set $IFS to only newline and tab.
# See also: http://www.dwheeler.com/essays/filenames-in-shell.html
IFS=$'\n\t'

# set -o xtrace # Print all executed commands

_usage() {
	cat <<- HEREDOC
		usage: ${0} <command>

		Commands:

		   run
		   build
		   test
		   credo
		   dialyzer
	HEREDOC
}

_main() {
	# Print usage if -h or --help given
	if  [[ "${1:-}" =~ ^-h|--help$  ]]; then
		_usage
		exit 0
	fi

	# Assign _command before nounset
	local _command="${1}"

	# Exit when accessing undeclared variables
	set -o nounset

	case "$_command" in
		build)
			docker-compose build
			;;
		run)
			shift
			docker-compose run --rm dev "$@"
			;;
		test)
			docker-compose run --rm dev mix test
			;;
		credo)
			docker-compose run --rm dev mix credo
			;;
		dialyzer)
			docker-compose run --rm dev mix dialyzer
			;;
		sh)
			docker-compose run --env PS1="\[\e[37m\][\[\e[m\]\[\e[32m\]dev\[\e[m\]\[\e[37m\]]\[\e[m\] \W \\$ " dev ash
			;;

		*)
			_usage
			exit 1
			;;
	esac
}

_main "$@"
